#config.yaml
server: https://cluster.k8s.net:9345 # Esta linha não e necessária na criacao do primeiro no server
token: 5d3f85fa37c618e1e8ef17f47f82db22 # Esse token pode ser gerado utilizando-se qualquer metodo a gosto.
tls-san:
  - cluster.k8s.net # Nome do cluster no balanceador

